In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [3]:
df1 = pd.read_csv('/home/senghakrou/stage-1/boamp_renewal_linking_quality/outputs/boamp_bias_report.csv')
df2 = pd.read_csv('/home/senghakrou/stage-1/boamp_renewal_linking_quality/outputs/boamp_linking_stats.csv')
df3 = pd.read_csv('/home/senghakrou/stage-1/boamp_renewal_linking_quality/outputs/boamp_renewal_candidates.csv')
df4 = pd.read_csv('/home/senghakrou/stage-1/boamp_renewal_linking_quality/outputs/boamp_renewal_links.csv')
df5 = pd.read_csv('/home/senghakrou/stage-1/data/processed/boamp_full_flat.csv')

In [4]:
df1.head()

,failure_reason,cpv_div2,n,pct_with_amount,median_duration,pct_duration_imputed,pct_siret_buyer,median_objet_len
0,CPV_MISMATCH,18.0,1,100.0,12.0,0.0,0.0,117.0
1,CPV_MISMATCH,22.0,1,100.0,12.0,0.0,0.0,105.0
2,CPV_MISMATCH,32.0,2,100.0,39.0,0.0,0.0,76.5
3,CPV_MISMATCH,33.0,1,0.0,NaN,100.0,0.0,129.0
4,CPV_MISMATCH,35.0,6,16.7,9.0,0.0,0.0,108.0

In [5]:
df2.head()

,total_ao,right_censored,eligible_ao,linked_events,unlinked,linking_rate_eligible_pct,linking_rate_all_pct,prev_baseline_pct,min_text_threshold,temporal_window_months,default_duration_months
0,1933,833,1100,697,403,63.36,36.06,11.3,0.2,12.0,48.0

In [6]:
df3.head()

,src_idweb,src_buyer_key,src_cpv,src_contract_start,src_duration_months,src_objet,cand_idweb,cand_contract_start,cand_cpv,cand_objet,gap_months,buyer_match_score,cpv_match_score,text_similarity_score,temporal_proximity_score,composite_score
0,15-31464,NAME:de la mayenne,NaN,2015-03-02,36.0,fourniture de petits materiels d'incendie et d...,17-176560,2017-12-17,35111200.0,Equipements pour Camions Citerne Grande Capaci...,33.54,1.0,0.5,0.6922,0.7951,0.7109
1,15-31464,NAME:de la mayenne,NaN,2015-03-02,36.0,fourniture de petits materiels d'incendie et d...,18-154990,2018-11-10,48613000.0,"acquisition, mise en oeuvre et maintenance d'u...",44.32,1.0,0.5,0.2740,0.3069,0.4460
2,15-136371,NAME:de la mayenne,NaN,2015-09-07,48.0,marché pour la fourniture des effets d'habille...,18-154990,2018-11-10,48613000.0,"acquisition, mise en oeuvre et maintenance d'u...",38.11,1.0,0.5,0.3593,0.1756,0.4538
3,16-183705,NAME:de la mayenne,35111200.0,2016-12-24,12.0,Equipements pour Fourgon Pompe Tonne (FPT) et ...,17-176560,2017-12-17,35111200.0,Equipements pour Camions Citerne Grande Capaci...,11.76,1.0,1.0,0.7269,0.9801,0.8868
4,16-183705,NAME:de la mayenne,35111200.0,2016-12-24,12.0,Equipements pour Fourgon Pompe Tonne (FPT) et ...,17-91530,2018-05-29,45212300.0,construction de l'équipement à vocations sport...,17.12,1.0,0.0,0.2022,0.5737,0.3456

In [7]:
df4.head()

,contract_id,buyer_key,cpv_div2,category_label,contract_start,declared_duration_months,dur_was_imputed,estimated_end_date,event,renewal_contract_id,observed_duration_months,composite_score,text_similarity,cpv_match_score,temporal_score,start_date_source,link_method
0,BOAMP:15-30947,NAME:smictom de la vallee de l authion,48.0,Software & Applications,2015-03-02,12.0,False,2016-03-01,0,NaN,118.00,NaN,NaN,NaN,NaN,publication_date,none
1,BOAMP:15-31464,NAME:de la mayenne,NaN,Unknown,2015-03-02,36.0,False,2018-03-01,1,BOAMP:17-176560,33.54,0.7109,0.6922,0.5,0.7951,publication_date,sentence_transformers
2,BOAMP:15-31513,NAME:reze,38.0,Unknown,2015-03-02,48.0,False,2019-03-02,1,BOAMP:19-87143,51.12,0.5076,0.2113,0.5,0.7403,publication_date,sentence_transformers
3,BOAMP:15-20937,NAME:nantes,44.0,Unknown,2015-03-03,48.0,False,2019-03-03,1,BOAMP:19-17307,47.17,0.8606,0.6860,1.0,0.9312,publication_date,sentence_transformers
4,BOAMP:15-32168,NAME:des pays de la loire,72.0,IT Services & Consulting,2015-07-21,24.0,False,2017-07-20,1,BOAMP:17-48788,24.11,0.7235,0.5009,0.7,0.9906,attribution_award_date,sentence_transformers

In [4]:
df5.head()

,idweb,dateparution,datefindiffusion,datelimitereponse,nomacheteur,code_departement,famille,nature,nature_libelle,type_procedure,...,cpv_principal,cpv_all,buyer_siret,buyer_cp,buyer_ville,amount_eur,duration_months,duration_source_field,date_attribution,date_publication_anterieure
0,15-30947,2015-03-02,2015-03-27,2015-03-27T11:30:00+00:00,SMICTOM de la Vallée de l'Authion,49,JOUE,APPEL_OFFRE,Avis de marché,OUVERT,...,48000000.0,48000000,NaN,49250,Beaufort en vallee,150000.0,12.0,DUREE_MOIS,NaN,NaN
1,15-31464,2015-03-02,2015-04-24,2015-04-24T15:00:00+00:00,Sdis de la Mayenne,53,JOUE,APPEL_OFFRE,Avis de marché,OUVERT,...,NaN,None|35311400|31121000|34928410|44423200|43830...,NaN,53005,Laval cedex,NaN,36.0,DUREE_MOIS,NaN,NaN
2,15-31513,2015-03-02,2015-04-17,2015-04-17T11:00:00+00:00,Ville de Rezé,44,JOUE,APPEL_OFFRE,Avis de marché,OUVERT,...,38720000.0,38720000|31224500|48620000,NaN,44403,Rezé Cedex,NaN,48.0,DUREE_MOIS,NaN,NaN
3,15-20937,2015-03-03,2015-04-14,2015-04-14T11:00:00+00:00,Ville de Nantes,44,JOUE,APPEL_OFFRE,Avis de marché,OUVERT,...,44512000.0,44512000|None|31000000|44810000|31500000|44522...,NaN,44000,nantes,NaN,48.0,DUREE_MOIS,NaN,NaN
4,15-31397,2015-03-03,2015-04-01,NaN,SDIS de la Sarthe,72,JOUE,ATTRIBUTION,Résultat de marché,NEGOCIE,...,48814300.0,48814300,NaN,72190,COULAINES,NaN,NaN,NaN,2015-02-17,NaN